# Generated by Django 5.1.7 on 2025-03-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.IntegerField(default=-1),
        ),
    ]
