# Generated by Django 5.1 on 2025-03-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='not_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
