# Generated by Django 5.1.7 on 2025-03-28 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_not_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='not_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='reciever',
        ),
        migrations.AddField(
            model_name='notification',
            name='content_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.CharField(default='video', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='real_content_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='recievers',
            field=models.ManyToManyField(related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
