# Generated by Django 5.1 on 2025-03-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(default='departments/images/department/default.jpg', null=True, upload_to='departments/images/department/')),
            ],
        ),
    ]
