# Generated by Django 5.1 on 2025-03-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_department_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(default='images/department/default.jpg', null=True, upload_to='images/department/'),
        ),
    ]
