# Generated by Django 5.1 on 2025-03-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(default='This course provides a comprehensive overview of essential topics, methodologies, and concepts. Further details will be provided.)  # Description of the course'),
        ),
    ]
