# Generated by Django 5.1 on 2025-03-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_course_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='images/course/default.jpg', null=True, upload_to='images/course/'),
        ),
    ]
