# Generated by Django 5.1 on 2025-03-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_remove_faculty_department_faculty_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='image',
            field=models.ImageField(default='images/faculty/default.jpg', null=True, upload_to='images/faculty/'),
        ),
    ]
