# Generated by Django 5.1.7 on 2025-03-25 17:36

import lms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=models.FileField(upload_to=lms.models.slide_upload_to),
        ),
    ]
