# Generated by Django 5.1.7 on 2025-03-26 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_note_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='courses_administered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faculty',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='faculty_moderated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(default='This course provides a comprehensive overview of essential topics, methodologies, and concepts. Further details will be provided.'),
        ),
    ]
