# Generated by Django 5.1.7 on 2025-03-26 23:35

import django.db.models.deletion
import lms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_course_admins_faculty_moderators_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.FileField(upload_to=lms.models.temp_note_upload_to)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_notes', to='lms.faculty')),
                ('real', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_versions', to='lms.note')),
            ],
        ),
        migrations.CreateModel(
            name='temp_Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.FileField(upload_to=lms.models.temp_slide_upload_to)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_slides', to='lms.faculty')),
                ('real', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_versions', to='lms.slide')),
            ],
        ),
        migrations.CreateModel(
            name='temp_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.FileField(upload_to=lms.models.temp_video_upload_to)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_videos', to='lms.faculty')),
                ('real', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_versions', to='lms.video')),
            ],
        ),
    ]
