# Generated by Django 5.1.7 on 2025-03-26 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_temp_note_temp_slide_temp_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_note',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='temp_slide',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='temp_video',
            name='faculty',
        ),
    ]
